// Claude RTL Toolkit - config.js
// Shared between content.js and the options page. Loaded first in both contexts,
// so these constants are available to the scripts that follow.

const SETTINGS_KEY = 'claude-rtl-settings';
const UI_LANG_KEY = 'claude-rtl-ui-lang';
const ENABLED_KEY = 'claude-rtl-enabled';

// UI languages for the options page. `rtl: true` flips the page direction.
const UI_LANGS = [
  { code: 'en', label: 'English', rtl: false },
  { code: 'fa', label: 'فارسی', rtl: true },
  { code: 'he', label: 'עברית', rtl: true },
  { code: 'ar', label: 'العربية', rtl: true },
  { code: 'ur', label: 'اردو', rtl: true },
];

// Translation table. Keys map to [data-i18n] attributes in options.html.
const I18N = {
  en: {
    title: 'Claude RTL Toolkit — Settings',
    subtitle: 'Set the font and text size for each section independently.',
    langLabel: 'Language',
    userGroup: '📝 User messages',
    claudeGroup: '✨ Claude responses',
    composerGroup: '⌨️ Message input',
    codeGroup: '💻 Code (independent)',
    font: 'Font',
    size: 'Size',
    lineNumbers: 'Show line numbers',
    reset: 'Reset to defaults',
    saved: '✓ Saved',
    resetDone: 'Reset to defaults',
    previewUser: 'Hello, this is a sample sentence. Sample 123.',
    previewClaude: "Claude's answer appears here. Sample 123.",
    previewComposer: 'Type your message here. Sample 123.',
    optDefault: 'default',
    optSystemFont: 'System font',
    optSerif: 'serif',
    optLigature: 'with ligatures',
    optSystemMono: 'System monospace',
    optHebrew: 'Hebrew + Latin',
    lineHeight: 'Line height',
    exportBtn: 'Export',
    importBtn: 'Import',
    importError: 'Invalid settings file',
    switchTo: 'Switch to',
    pEnabled: 'Extension enabled',
    pAllRtl: 'Set all → RTL',
    pAllLtr: 'Set all → LTR',
    pSettings: 'Open settings ⚙',
    pDetected: 'messages on this page',
    pNoPage: 'Open claude.ai to use this.',
  },
  fa: {
    title: 'تنظیمات Claude RTL Toolkit',
    subtitle: 'فونت و اندازه‌ی متن را برای هر بخش جداگانه تنظیم کن.',
    langLabel: 'زبان',
    userGroup: '📝 پرسش‌های کاربر',
    claudeGroup: '✨ پاسخ‌های Claude',
    composerGroup: '⌨️ کادر تایپ پیام',
    codeGroup: '💻 کدها (مستقل)',
    font: 'فونت',
    size: 'اندازه',
    lineNumbers: 'نمایش شماره خط',
    reset: 'بازنشانی به پیش‌فرض',
    saved: '✓ ذخیره شد',
    resetDone: 'به پیش‌فرض بازنشانی شد',
    previewUser: 'سلام، این یک نمونه متن فارسی است. Sample 123.',
    previewClaude: 'پاسخ Claude اینجا نمایش داده می‌شود. Sample 123.',
    previewComposer: 'پیامت را اینجا بنویس. Sample 123.',
    optDefault: 'پیش‌فرض',
    optSystemFont: 'فونت سیستم',
    optSerif: 'سریف',
    optLigature: 'با ligature',
    optSystemMono: 'مونواسپیس سیستم',
    optHebrew: 'عبری + لاتین',
    lineHeight: 'فاصله‌ی خطوط',
    exportBtn: 'خروجی گرفتن',
    importBtn: 'وارد کردن',
    importError: 'فایل تنظیمات نامعتبر',
    switchTo: 'تغییر به',
    pEnabled: 'افزونه فعال',
    pAllRtl: 'همه → RTL',
    pAllLtr: 'همه → LTR',
    pSettings: 'باز کردن تنظیمات ⚙',
    pDetected: 'پیام در این صفحه',
    pNoPage: 'برای استفاده، claude.ai را باز کن.',
  },
  he: {
    title: 'הגדרות Claude RTL Toolkit',
    subtitle: 'הגדר את הגופן וגודל הטקסט עבור כל מקטע בנפרד.',
    langLabel: 'שפה',
    userGroup: '📝 הודעות המשתמש',
    claudeGroup: '✨ תשובות Claude',
    composerGroup: '⌨️ תיבת ההקלדה',
    codeGroup: '💻 קוד (עצמאי)',
    font: 'גופן',
    size: 'גודל',
    lineNumbers: 'הצג מספרי שורות',
    reset: 'אפס לברירת מחדל',
    saved: '✓ נשמר',
    resetDone: 'אופס לברירת מחדל',
    previewUser: 'שלום, זהו משפט לדוגמה. Sample 123.',
    previewClaude: 'התשובה של Claude מופיעה כאן. Sample 123.',
    previewComposer: 'הקלד את ההודעה שלך כאן. Sample 123.',
    optDefault: 'ברירת מחדל',
    optSystemFont: 'גופן מערכת',
    optSerif: 'סריף',
    optLigature: 'עם ליגטורות',
    optSystemMono: 'Monospace מערכת',
    optHebrew: 'עברית + לטינית',
    lineHeight: 'גובה שורה',
    exportBtn: 'ייצוא',
    importBtn: 'ייבוא',
    importError: 'קובץ הגדרות לא תקין',
    switchTo: 'החלף ל־',
    pEnabled: 'התוסף פעיל',
    pAllRtl: 'הכול → RTL',
    pAllLtr: 'הכול → LTR',
    pSettings: 'פתח הגדרות ⚙',
    pDetected: 'הודעות בדף זה',
    pNoPage: 'פתח את claude.ai כדי להשתמש.',
  },
  ar: {
    title: 'إعدادات Claude RTL Toolkit',
    subtitle: 'اضبط الخط وحجم النص لكل قسم على حدة.',
    langLabel: 'اللغة',
    userGroup: '📝 رسائل المستخدم',
    claudeGroup: '✨ ردود Claude',
    composerGroup: '⌨️ مربع كتابة الرسالة',
    codeGroup: '💻 الشيفرة (مستقلة)',
    font: 'الخط',
    size: 'الحجم',
    lineNumbers: 'إظهار أرقام الأسطر',
    reset: 'إعادة التعيين إلى الافتراضي',
    saved: '✓ تم الحفظ',
    resetDone: 'تمت إعادة التعيين إلى الافتراضي',
    previewUser: 'مرحبًا، هذه جملة نموذجية. Sample 123.',
    previewClaude: 'تظهر إجابة Claude هنا. Sample 123.',
    previewComposer: 'اكتب رسالتك هنا. Sample 123.',
    optDefault: 'افتراضي',
    optSystemFont: 'خط النظام',
    optSerif: 'سيريف',
    optLigature: 'مع الحروف المركبة',
    optSystemMono: 'أحادي المسافة للنظام',
    optHebrew: 'عبري + لاتيني',
    lineHeight: 'ارتفاع السطر',
    exportBtn: 'تصدير',
    importBtn: 'استيراد',
    importError: 'ملف إعدادات غير صالح',
    switchTo: 'التبديل إلى',
    pEnabled: 'الإضافة مفعّلة',
    pAllRtl: 'الكل → RTL',
    pAllLtr: 'الكل → LTR',
    pSettings: 'فتح الإعدادات ⚙',
    pDetected: 'رسائل في هذه الصفحة',
    pNoPage: 'افتح claude.ai للاستخدام.',
  },
  ur: {
    title: 'Claude RTL Toolkit کی ترتیبات',
    subtitle: 'ہر حصے کے لیے فونٹ اور متن کا سائز الگ الگ مقرر کریں۔',
    langLabel: 'زبان',
    userGroup: '📝 صارف کے پیغامات',
    claudeGroup: '✨ Claude کے جوابات',
    composerGroup: '⌨️ پیغام لکھنے کا خانہ',
    codeGroup: '💻 کوڈ (خودمختار)',
    font: 'فونٹ',
    size: 'سائز',
    lineNumbers: 'سطر نمبر دکھائیں',
    reset: 'طے شدہ پر بحال کریں',
    saved: '✓ محفوظ ہو گیا',
    resetDone: 'طے شدہ پر بحال',
    previewUser: 'سلام، یہ ایک نمونہ جملہ ہے۔ Sample 123.',
    previewClaude: 'Claude کا جواب یہاں ظاہر ہوتا ہے۔ Sample 123.',
    previewComposer: 'اپنا پیغام یہاں لکھیں۔ Sample 123.',
    optDefault: 'طے شدہ',
    optSystemFont: 'سسٹم فونٹ',
    optSerif: 'سیریف',
    optLigature: 'لگیچر کے ساتھ',
    optSystemMono: 'سسٹم مونو اسپیس',
    optHebrew: 'عبرانی + لاطینی',
    lineHeight: 'سطر کی اونچائی',
    exportBtn: 'ایکسپورٹ',
    importBtn: 'امپورٹ',
    importError: 'غلط ترتیبات فائل',
    switchTo: 'تبدیل کریں',
    pEnabled: 'ایکسٹینشن فعال',
    pAllRtl: 'سب → RTL',
    pAllLtr: 'سب → LTR',
    pSettings: 'ترتیبات کھولیں ⚙',
    pDetected: 'اس صفحے پر پیغامات',
    pNoPage: 'استعمال کے لیے claude.ai کھولیں۔',
  },
};

// Curated font choices shown in the options dropdowns. `value` is a full CSS
// font-family stack. `name` is a brand string (never translated). `descKey` /
// `nameKey` reference I18N entries so the human label is localized per UI language.
const FONT_OPTIONS = {
  text: [
    { name: 'Vazirmatn', descKey: 'optDefault', value: "'Vazirmatn', system-ui, sans-serif" },
    { name: 'Estedad', value: "'Estedad', system-ui, sans-serif" },
    { name: 'Rubik', descKey: 'optHebrew', value: "'Rubik', system-ui, sans-serif" },
    { nameKey: 'optSystemFont', value: 'system-ui, -apple-system, sans-serif' },
    { name: 'Tahoma', value: 'Tahoma, sans-serif' },
    { name: 'Arial', value: 'Arial, Helvetica, sans-serif' },
    { name: 'Georgia', descKey: 'optSerif', value: 'Georgia, serif' },
  ],
  code: [
    { name: 'JetBrains Mono', descKey: 'optLigature', value: "'JetBrains Mono', ui-monospace, monospace" },
    { nameKey: 'optSystemMono', value: 'ui-monospace, SFMono-Regular, Menlo, Consolas, monospace' },
    { name: 'Menlo', value: 'Menlo, monospace' },
    { name: 'Consolas', value: 'Consolas, monospace' },
    { name: 'Courier New', value: "'Courier New', monospace" },
  ],
};

const DEFAULT_SETTINGS = {
  user:     { fontFamily: "'Vazirmatn', system-ui, sans-serif", fontSize: 16, lineHeight: 1.7 },
  claude:   { fontFamily: "'Vazirmatn', system-ui, sans-serif", fontSize: 16, lineHeight: 1.7 },
  composer: { fontFamily: "'Vazirmatn', system-ui, sans-serif", fontSize: 16, lineHeight: 1.7 },
  // JetBrains Mono ships programming ligatures (-> ≠ => …); lineNumbers is opt-in.
  code:     { fontFamily: "'JetBrains Mono', ui-monospace, monospace", fontSize: 14, lineNumbers: false },
};

// Merge stored settings over defaults so missing keys always have a value.
function mergeSettings(stored) {
  const s = stored || {};
  return {
    user:     { ...DEFAULT_SETTINGS.user,     ...(s.user     || {}) },
    claude:   { ...DEFAULT_SETTINGS.claude,   ...(s.claude   || {}) },
    composer: { ...DEFAULT_SETTINGS.composer, ...(s.composer || {}) },
    code:     { ...DEFAULT_SETTINGS.code,     ...(s.code     || {}) },
  };
}
